version: '3.7'

services:
  db:
    build: .
    environment:
      MYSQL_DATABASE: jdsports
      MYSQL_USER: jdsports_user
      MYSQL_PASSWORD: jdsports_password
      MYSQL_ROOT_PASSWORD: jdsports_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
